// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSwJTuUK-G4QsdQXepnQFCXTLEk6bmY2E',
    appId: '1:296497583713:web:c79a6fcb518a5cdbb0fc20',
    messagingSenderId: '296497583713',
    projectId: 'our-chat-87c52',
    authDomain: 'our-chat-87c52.firebaseapp.com',
    storageBucket: 'our-chat-87c52.firebasestorage.app',
    measurementId: 'G-BV7WYRFZBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBktH3smgAQ57W4F8pr_8mEMq4clzDwW9s',
    appId: '1:296497583713:android:0d6646f3e8cffa08b0fc20',
    messagingSenderId: '296497583713',
    projectId: 'our-chat-87c52',
    storageBucket: 'our-chat-87c52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjeh7tVFVZBlvbykSyrV3yNCZAAJBVS5Q',
    appId: '1:296497583713:ios:aa49ff1de47bb50db0fc20',
    messagingSenderId: '296497583713',
    projectId: 'our-chat-87c52',
    storageBucket: 'our-chat-87c52.firebasestorage.app',
    iosBundleId: 'com.example.ourChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjeh7tVFVZBlvbykSyrV3yNCZAAJBVS5Q',
    appId: '1:296497583713:ios:aa49ff1de47bb50db0fc20',
    messagingSenderId: '296497583713',
    projectId: 'our-chat-87c52',
    storageBucket: 'our-chat-87c52.firebasestorage.app',
    iosBundleId: 'com.example.ourChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSwJTuUK-G4QsdQXepnQFCXTLEk6bmY2E',
    appId: '1:296497583713:web:c7d614a5c570a1c1b0fc20',
    messagingSenderId: '296497583713',
    projectId: 'our-chat-87c52',
    authDomain: 'our-chat-87c52.firebaseapp.com',
    storageBucket: 'our-chat-87c52.firebasestorage.app',
    measurementId: 'G-PX2V30LMBN',
  );
}
